// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pnj_generator.Data;

#nullable disable

namespace pnj_generator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214111602_UpdateCharacteristic")]
    partial class UpdateCharacteristic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pnj_generator.Models.Features.Characteristic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("HasModifiers")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxDice")
                        .HasColumnType("integer");

                    b.Property<int>("MinDice")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId");

                    b.ToTable("characteristics", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Malus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.AdditionalInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId");

                    b.ToTable("additionalInformations", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.FragmentIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId");

                    b.ToTable("fragmentIdentities", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AliasId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CultureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FirstNameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<Guid?>("NameId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SpecieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AliasId");

                    b.HasIndex("AlignmentId");

                    b.HasIndex("CultureId");

                    b.HasIndex("FirstNameId");

                    b.HasIndex("NameId");

                    b.HasIndex("OriginId");

                    b.HasIndex("SpecieId");

                    b.HasIndex("UniverseId");

                    b.ToTable("identities", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Protection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArmorRating")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId");

                    b.ToTable("protections", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bonus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Malus")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Prerequisites")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RelatedCharacteristic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Trait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Prerequisites")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId");

                    b.ToTable("traits", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Weapons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Radius")
                        .HasColumnType("integer");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeaponFireMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId");

                    b.ToTable("weapons", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Rules.ModifierRules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AvailableValue")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CharacteristicId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Modifier")
                        .HasColumnType("integer");

                    b.Property<int?>("RangeMax")
                        .HasColumnType("integer");

                    b.Property<int?>("RangeMin")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("UniverseId");

                    b.ToTable("modifierRules", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Universe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiceRule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasModifiers")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModifierType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("universes", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.Alignment", b =>
                {
                    b.HasBaseType("pnj_generator.Models.Features.Identities.AdditionalInformation");

                    b.ToTable("alignments", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.Culture", b =>
                {
                    b.HasBaseType("pnj_generator.Models.Features.Identities.AdditionalInformation");

                    b.ToTable("cultures", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.Origin", b =>
                {
                    b.HasBaseType("pnj_generator.Models.Features.Identities.AdditionalInformation");

                    b.ToTable("origins", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.Specie", b =>
                {
                    b.HasBaseType("pnj_generator.Models.Features.Identities.AdditionalInformation");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Characteristic", b =>
                {
                    b.HasOne("pnj_generator.Models.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Equipment", b =>
                {
                    b.HasOne("pnj_generator.Models.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.AdditionalInformation", b =>
                {
                    b.HasOne("pnj_generator.Models.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.FragmentIdentity", b =>
                {
                    b.HasOne("pnj_generator.Models.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.Identity", b =>
                {
                    b.HasOne("pnj_generator.Models.Features.Identities.FragmentIdentity", "Alias")
                        .WithMany()
                        .HasForeignKey("AliasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pnj_generator.Models.Features.Identities.Alignment", "Alignment")
                        .WithMany()
                        .HasForeignKey("AlignmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pnj_generator.Models.Features.Identities.Culture", "Culture")
                        .WithMany()
                        .HasForeignKey("CultureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pnj_generator.Models.Features.Identities.FragmentIdentity", "FirstName")
                        .WithMany()
                        .HasForeignKey("FirstNameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pnj_generator.Models.Features.Identities.FragmentIdentity", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pnj_generator.Models.Features.Identities.Origin", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pnj_generator.Models.Features.Identities.Specie", "Specie")
                        .WithMany()
                        .HasForeignKey("SpecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pnj_generator.Models.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alias");

                    b.Navigation("Alignment");

                    b.Navigation("Culture");

                    b.Navigation("FirstName");

                    b.Navigation("Name");

                    b.Navigation("Origin");

                    b.Navigation("Specie");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Protection", b =>
                {
                    b.HasOne("pnj_generator.Models.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Skill", b =>
                {
                    b.HasOne("pnj_generator.Models.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Trait", b =>
                {
                    b.HasOne("pnj_generator.Models.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Weapons", b =>
                {
                    b.HasOne("pnj_generator.Models.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("pnj_generator.Models.Rules.ModifierRules", b =>
                {
                    b.HasOne("pnj_generator.Models.Features.Characteristic", "Characteristic")
                        .WithMany()
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("pnj_generator.Models.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characteristic");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.Alignment", b =>
                {
                    b.HasOne("pnj_generator.Models.Features.Identities.AdditionalInformation", null)
                        .WithOne()
                        .HasForeignKey("pnj_generator.Models.Features.Identities.Alignment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.Culture", b =>
                {
                    b.HasOne("pnj_generator.Models.Features.Identities.AdditionalInformation", null)
                        .WithOne()
                        .HasForeignKey("pnj_generator.Models.Features.Identities.Culture", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.Origin", b =>
                {
                    b.HasOne("pnj_generator.Models.Features.Identities.AdditionalInformation", null)
                        .WithOne()
                        .HasForeignKey("pnj_generator.Models.Features.Identities.Origin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pnj_generator.Models.Features.Identities.Specie", b =>
                {
                    b.HasOne("pnj_generator.Models.Features.Identities.AdditionalInformation", null)
                        .WithOne()
                        .HasForeignKey("pnj_generator.Models.Features.Identities.Specie", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
